spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: koorung
    password: test1234
    url: jdbc:postgresql://localhost:5432/kotlin_playground

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false